version: "3.5"

networks:
  node-react:
    driver: bridge
    name: node_react

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  db:
    image: postgres
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    networks:
      - node-react
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: api
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - node-react
    ports:
      - 8080:8080

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  server:
    image: node:alpine
    volumes:
      - "./server:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "password"
      MONGODB_DBNAME: "SampleCollections"
      DATABASE_URL: "postgres://root:password@db/payment"
      JWT_SECRET: "MyBestSecret"
    depends_on:
      - db
    command: "npm start"
    networks:
      - node-react
    ports:
      - 127.0.0.1:3000:3000

  scrapper:
    image: node:alpine
    volumes:
      - "./server:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    networks:
      - node-react
    depends_on:
      - db
    command: "npm run scrapper"
    environment:
      DATABASE_URL: "postgres://root:password@db/payment"
    ports:
      - 127.0.0.1:3003:3000

  client:
    build: "./client"
    volumes:
      - "./client:/home/node/app"
    working_dir: "/home/node/app"
    command: "yarn start"
    tty: true
    stdin_open: true
    ports:
      - 127.0.0.1:3001:3000

volumes:
  db-data: {}
