GET http://localhost:3000/merchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY3Mzk2MCwiZXhwIjoxNTkzNjc3NTYwfQ.RPvZxcn1D9e5UOT5Zsn6SKGHfSSKZuCGH6UKC7C3MAQ

###
GET http://localhost:3000/merchants/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY3Mzk2MCwiZXhwIjoxNTkzNjc3NTYwfQ.RPvZxcn1D9e5UOT5Zsn6SKGHfSSKZuCGH6UKC7C3MAQ

###
POST http://localhost:3000/merchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY3Mzk2MCwiZXhwIjoxNTkzNjc3NTYwfQ.RPvZxcn1D9e5UOT5Zsn6SKGHfSSKZuCGH6UKC7C3MAQ
Content-Type: application/json

{
  "name": "marchant",
  "KBISUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "currency": "EUR",
  "confirmUrl": "http://localhost:3004/orders/confirmation",
  "cancelUrl": "http://localhost:3004/orders/cancel",
  "contactName": "Marcel Patoulachi",
  "email": "fake@email.fake",
  "phoneNumber": "0100000000",
  "address": {
    "fullName": "Marcel Patoulachi",
    "address": "place de la tour Eiffel",
    "town": "Paris",
    "zip": "75001",
    "country": "France"
  }
}

###
PUT http://localhost:3000/merchants/10/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY3Mzk2MCwiZXhwIjoxNTkzNjc3NTYwfQ.RPvZxcn1D9e5UOT5Zsn6SKGHfSSKZuCGH6UKC7C3MAQ

###
GET http://localhost:3000/merchants/10/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY5Njc0MCwiZXhwIjoxNTkzNzAwMzQwfQ.Ug4ALQHsXRKfvVQHGKqYhSAKPgYGc-I7jblBYs-ceds

###
GET http://localhost:3000/merchants/10/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY5Njc0MCwiZXhwIjoxNTkzNzAwMzQwfQ.Ug4ALQHsXRKfvVQHGKqYhSAKPgYGc-I7jblBYs-ceds

###
DELETE http://localhost:3000/merchants/10/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY5Njc0MCwiZXhwIjoxNTkzNzAwMzQwfQ.Ug4ALQHsXRKfvVQHGKqYhSAKPgYGc-I7jblBYs-ceds
