GET http://localhost:3000/merchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzcwMTYyMywiZXhwIjoxNTkzNzA1MjIzfQ.lw7DsOO-x_skZSLCMjm0lVCJTuoANLoOAn3Uxf88mvI

###
GET http://localhost:3000/merchants/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzcwMTYyMywiZXhwIjoxNTkzNzA1MjIzfQ.lw7DsOO-x_skZSLCMjm0lVCJTuoANLoOAn3Uxf88mvI

###
POST http://localhost:3000/merchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzk3NjE5OSwiZXhwIjoxNTkzOTc5Nzk5fQ.zZEM9OzBI1K-cUKrWijUFmWekMpIHQChr5lZpb6P3nU
Content-Type: application/json

{
  "name": "michel",
  "KBISUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "currency": "EUR",
  "confirmUrl": "http://merchant-api:3000/orders/confirmation",
  "cancelUrl": "http://merchant-api:3000/orders/cancel",
  "contactName": "Marcel Patoulachi",
  "email": "fake@email.fake",
  "phoneNumber": "0100000000",
  "address": {
    "fullName": "Marcel Patoulachi",
    "address": "place de la tour Eiffel",
    "town": "Paris",
    "zip": "75001",
    "country": "France"
  }
}

###
PUT http://localhost:3000/merchants/20/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzk3NjE5OSwiZXhwIjoxNTkzOTc5Nzk5fQ.zZEM9OzBI1K-cUKrWijUFmWekMpIHQChr5lZpb6P3nU

###
GET http://localhost:3000/merchants/10/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzcwMTYyMywiZXhwIjoxNTkzNzA1MjIzfQ.lw7DsOO-x_skZSLCMjm0lVCJTuoANLoOAn3Uxf88mvI

###
GET http://localhost:3000/merchants/10/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzc2Mzg2NSwiZXhwIjoxNTkzNzY3NDY1fQ.L_33mBuaOlUuEjHCFilH6Z2l-0JLUkkivPiwTCvJHjI

###
DELETE http://localhost:3000/merchants/10/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzcwMTYyMywiZXhwIjoxNTkzNzA1MjIzfQ.lw7DsOO-x_skZSLCMjm0lVCJTuoANLoOAn3Uxf88mvI
