###
POST http://localhost:3000/transactions/3/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttYXJxdWVzQHZldGl4eTcuZnIiLCJpYXQiOjE1OTI1NjU4OTcsImV4cCI6MTU5MjU2OTQ5N30.P7tLk53cajOAiXgsYCP16-n_qpTHNiVE29qUk_l2YKs
Content-Type: application/json

{
  "amount": 1050,
  "creditCardInfo": {
    "CCNumber": "12345",
    "expirationDate": "01/22",
    "secureCode": "123"
  }
}

###
POST http://localhost:3000/transactions/18/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttYXJxdWVzQHZldGl4eTcuZnIiLCJpYXQiOjE1OTI1NjU4OTcsImV4cCI6MTU5MjU2OTQ5N30.P7tLk53cajOAiXgsYCP16-n_qpTHNiVE29qUk_l2YKs

###
POST http://localhost:3000/transactions/31/refund
Authorization: Basic MTQxMmI4ZTMtNzhmNi00ZmY2LWJiNWItOGJjYzc1OWU2NGRhOmxjc2Ezemh1
Content-Type: application/json

{
  "amount": 200
}


###
POST http://localhost:3000/transactions
Authorization: Basic NTE2NzVmZTgtNzQ2OC00Y2U4LWJmMDEtZTcwYjY0ZTU0NzljOjMzeG0zbWR2
Content-Type: application/json

{
  "customerId": "1",
  "tag": "orderId: 12341234",
  "orderId": "3",
  "cart": {
    "patrick": 2,
    "michel": 3
  },
  "amount": 1050,
  "billing": {
    "fullName": "Marcel Patoulachi",
    "address": "place de la tour Eiffel",
    "town": "Paris",
    "zip": "75001",
    "country": "France"
  },
  "shipping": {
    "fullName": "Marcel Patoulachi",
    "address": "place de la tour Eiffel",
    "town": "Paris",
    "zip": "75001",
    "country": "France"
  },
  "merchantId": 19
}

###
GET http://localhost:3000/transactions/30
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzc2Mzg2NSwiZXhwIjoxNTkzNzY3NDY1fQ.L_33mBuaOlUuEjHCFilH6Z2l-0JLUkkivPiwTCvJHjI
Authorization: Basic MTQxMmI4ZTMtNzhmNi00ZmY2LWJiNWItOGJjYzc1OWU2NGRhOmxjc2Ezemh1

###
GET http://localhost:3000/transactions
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzc2Mzg2NSwiZXhwIjoxNTkzNzY3NDY1fQ.L_33mBuaOlUuEjHCFilH6Z2l-0JLUkkivPiwTCvJHjI
Authorization: Basic MTQxMmI4ZTMtNzhmNi00ZmY2LWJiNWItOGJjYzc1OWU2NGRhOmxjc2Ezemh1

###
PUT http://localhost:3000/transactions/31/confirm
