###
POST http://localhost:3000/login_check
Content-Type: application/json

{
  "username": "fake@email.fake",
  "password": "test"
}


###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5MzY3Mzk2MCwiZXhwIjoxNTkzNjc3NTYwfQ.RPvZxcn1D9e5UOT5Zsn6SKGHfSSKZuCGH6UKC7C3MAQ

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "fake@email.fake",
  "password": "test",
  "role": "admin"
}

###
GET http://localhost:3000/users/2

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "fake@email.fake",
  "password": "test"
}

###
DELETE http://localhost:3000/users/2
